//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class GrammarParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, ADDARRAY=13, AND=14, OR=15, LT=16, GT=17, 
		GTEQ=18, LTEQ=19, NEQ=20, EQ=21, INTDECL=22, FLOATDECL=23, BOOLDECL=24, 
		LISTDECL=25, VOID=26, IF=27, ELSEIF=28, ELSE=29, WHILE=30, FOR=31, MUL=32, 
		DIV=33, ADD=34, SUB=35, BOOL=36, IDENTIFIER=37, INT=38, FLOAT=39, COMMENT=40, 
		WS=41;
	public const int
		RULE_program = 0, RULE_stmts = 1, RULE_stmt = 2, RULE_var_stmt = 3, RULE_var_decl = 4, 
		RULE_cond_stmt = 5, RULE_parameter_decl = 6, RULE_func_stmt = 7, RULE_func_expr = 8, 
		RULE_iter_stmt = 9, RULE_print = 10, RULE_expr = 11, RULE_var_expr = 12, 
		RULE_num_expr = 13, RULE_logic_expr = 14, RULE_return_stmt = 15, RULE_compileUnit = 16;
	public static readonly string[] ruleNames = {
		"program", "stmts", "stmt", "var_stmt", "var_decl", "cond_stmt", "parameter_decl", 
		"func_stmt", "func_expr", "iter_stmt", "print", "expr", "var_expr", "num_expr", 
		"logic_expr", "return_stmt", "compileUnit"
	};

	private static readonly string[] _LiteralNames = {
		null, "'Program'", "'{'", "'}'", "'='", "'['", "']'", "','", "'('", "')'", 
		"'to'", "'print'", "'return'", "'add'", null, null, "'<'", "'>'", "'>='", 
		"'<='", "'!='", "'=='", "'int'", "'float'", "'bool'", "'[]'", "'void'", 
		"'if'", "'elseif'", "'else'", "'while'", "'for'", "'*'", "'/'", "'+'", 
		"'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "ADDARRAY", "AND", "OR", "LT", "GT", "GTEQ", "LTEQ", "NEQ", "EQ", 
		"INTDECL", "FLOATDECL", "BOOLDECL", "LISTDECL", "VOID", "IF", "ELSEIF", 
		"ELSE", "WHILE", "FOR", "MUL", "DIV", "ADD", "SUB", "BOOL", "IDENTIFIER", 
		"INT", "FLOAT", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Grammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GrammarParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public GrammarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public GrammarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		public Var_stmtContext[] var_stmt() {
			return GetRuleContexts<Var_stmtContext>();
		}
		public Var_stmtContext var_stmt(int i) {
			return GetRuleContext<Var_stmtContext>(i);
		}
		public Func_stmtContext[] func_stmt() {
			return GetRuleContexts<Func_stmtContext>();
		}
		public Func_stmtContext func_stmt(int i) {
			return GetRuleContext<Func_stmtContext>(i);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 38;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INTDECL) | (1L << FLOATDECL) | (1L << BOOLDECL) | (1L << VOID) | (1L << IDENTIFIER))) != 0)) {
				{
				State = 36;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case IDENTIFIER:
					{
					State = 34; var_stmt();
					}
					break;
				case INTDECL:
				case FLOATDECL:
				case BOOLDECL:
				case VOID:
					{
					State = 35; func_stmt();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 40;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 41; Match(T__0);
			State = 42; Match(T__1);
			State = 44;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				{
				State = 43; stmts();
				}
				break;
			}
			State = 46; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtsContext : ParserRuleContext {
		public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public StmtsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmts; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterStmts(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitStmts(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmts(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtsContext stmts() {
		StmtsContext _localctx = new StmtsContext(Context, State);
		EnterRule(_localctx, 2, RULE_stmts);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__10) | (1L << INTDECL) | (1L << FLOATDECL) | (1L << BOOLDECL) | (1L << IF) | (1L << WHILE) | (1L << FOR) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 48; stmt();
				}
				}
				State = 53;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		public Var_stmtContext var_stmt() {
			return GetRuleContext<Var_stmtContext>(0);
		}
		public Var_declContext var_decl() {
			return GetRuleContext<Var_declContext>(0);
		}
		public Iter_stmtContext iter_stmt() {
			return GetRuleContext<Iter_stmtContext>(0);
		}
		public Cond_stmtContext cond_stmt() {
			return GetRuleContext<Cond_stmtContext>(0);
		}
		public Func_exprContext func_expr() {
			return GetRuleContext<Func_exprContext>(0);
		}
		public PrintContext print() {
			return GetRuleContext<PrintContext>(0);
		}
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterStmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitStmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(Context, State);
		EnterRule(_localctx, 4, RULE_stmt);
		try {
			State = 60;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 54; var_stmt();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 55; var_decl();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 56; iter_stmt();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 57; cond_stmt();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 58; func_expr();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 59; print();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_stmtContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GrammarParser.IDENTIFIER, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Logic_exprContext logic_expr() {
			return GetRuleContext<Logic_exprContext>(0);
		}
		public Num_exprContext num_expr() {
			return GetRuleContext<Num_exprContext>(0);
		}
		public ITerminalNode ADDARRAY() { return GetToken(GrammarParser.ADDARRAY, 0); }
		public Var_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterVar_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitVar_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_stmtContext var_stmt() {
		Var_stmtContext _localctx = new Var_stmtContext(Context, State);
		EnterRule(_localctx, 6, RULE_var_stmt);
		try {
			State = 83;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 62; Match(IDENTIFIER);
				State = 63; Match(T__3);
				State = 66;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
				case 1:
					{
					State = 64; expr();
					}
					break;
				case 2:
					{
					State = 65; logic_expr();
					}
					break;
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 68; Match(IDENTIFIER);
				State = 69; Match(T__4);
				State = 70; num_expr(0);
				State = 71; Match(T__5);
				State = 72; Match(T__3);
				State = 75;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
				case 1:
					{
					State = 73; expr();
					}
					break;
				case 2:
					{
					State = 74; logic_expr();
					}
					break;
				}
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 77; Match(IDENTIFIER);
				State = 78; Match(ADDARRAY);
				State = 81;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
				case 1:
					{
					State = 79; expr();
					}
					break;
				case 2:
					{
					State = 80; logic_expr();
					}
					break;
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_declContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GrammarParser.IDENTIFIER, 0); }
		public ITerminalNode INTDECL() { return GetToken(GrammarParser.INTDECL, 0); }
		public ITerminalNode FLOATDECL() { return GetToken(GrammarParser.FLOATDECL, 0); }
		public ITerminalNode BOOLDECL() { return GetToken(GrammarParser.BOOLDECL, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public Logic_exprContext[] logic_expr() {
			return GetRuleContexts<Logic_exprContext>();
		}
		public Logic_exprContext logic_expr(int i) {
			return GetRuleContext<Logic_exprContext>(i);
		}
		public ITerminalNode LISTDECL() { return GetToken(GrammarParser.LISTDECL, 0); }
		public Var_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_decl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterVar_decl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitVar_decl(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_declContext var_decl() {
		Var_declContext _localctx = new Var_declContext(Context, State);
		EnterRule(_localctx, 8, RULE_var_decl);
		int _la;
		try {
			State = 114;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 85;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INTDECL) | (1L << FLOATDECL) | (1L << BOOLDECL))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 86; Match(IDENTIFIER);
				State = 87; Match(T__3);
				State = 90;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
				case 1:
					{
					State = 88; expr();
					}
					break;
				case 2:
					{
					State = 89; logic_expr();
					}
					break;
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 92;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INTDECL) | (1L << FLOATDECL) | (1L << BOOLDECL))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 93; Match(LISTDECL);
				State = 94; Match(IDENTIFIER);
				State = 95; Match(T__3);
				State = 96; Match(T__4);
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__7) | (1L << BOOL) | (1L << IDENTIFIER) | (1L << INT) | (1L << FLOAT))) != 0)) {
					{
					State = 99;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
					case 1:
						{
						State = 97; expr();
						}
						break;
					case 2:
						{
						State = 98; logic_expr();
						}
						break;
					}
					State = 108;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__6) {
						{
						{
						State = 101; Match(T__6);
						State = 104;
						ErrorHandler.Sync(this);
						switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
						case 1:
							{
							State = 102; expr();
							}
							break;
						case 2:
							{
							State = 103; logic_expr();
							}
							break;
						}
						}
						}
						State = 110;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 113; Match(T__5);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cond_stmtContext : ParserRuleContext {
		public Logic_exprContext cond;
		public ITerminalNode IF() { return GetToken(GrammarParser.IF, 0); }
		public Logic_exprContext[] logic_expr() {
			return GetRuleContexts<Logic_exprContext>();
		}
		public Logic_exprContext logic_expr(int i) {
			return GetRuleContext<Logic_exprContext>(i);
		}
		public StmtsContext[] stmts() {
			return GetRuleContexts<StmtsContext>();
		}
		public StmtsContext stmts(int i) {
			return GetRuleContext<StmtsContext>(i);
		}
		public ITerminalNode[] ELSEIF() { return GetTokens(GrammarParser.ELSEIF); }
		public ITerminalNode ELSEIF(int i) {
			return GetToken(GrammarParser.ELSEIF, i);
		}
		public ITerminalNode ELSE() { return GetToken(GrammarParser.ELSE, 0); }
		public Cond_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cond_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterCond_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitCond_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCond_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cond_stmtContext cond_stmt() {
		Cond_stmtContext _localctx = new Cond_stmtContext(Context, State);
		EnterRule(_localctx, 10, RULE_cond_stmt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116; Match(IF);
			State = 117; _localctx.cond = logic_expr();
			State = 118; Match(T__1);
			State = 120;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				{
				State = 119; stmts();
				}
				break;
			}
			State = 122; Match(T__2);
			State = 133;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ELSEIF) {
				{
				{
				State = 123; Match(ELSEIF);
				State = 124; logic_expr();
				State = 125; Match(T__1);
				State = 127;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
				case 1:
					{
					State = 126; stmts();
					}
					break;
				}
				State = 129; Match(T__2);
				}
				}
				State = 135;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 142;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE) {
				{
				State = 136; Match(ELSE);
				State = 137; Match(T__1);
				State = 139;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
				case 1:
					{
					State = 138; stmts();
					}
					break;
				}
				State = 141; Match(T__2);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Parameter_declContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GrammarParser.IDENTIFIER, 0); }
		public ITerminalNode INTDECL() { return GetToken(GrammarParser.INTDECL, 0); }
		public ITerminalNode FLOATDECL() { return GetToken(GrammarParser.FLOATDECL, 0); }
		public ITerminalNode BOOLDECL() { return GetToken(GrammarParser.BOOLDECL, 0); }
		public ITerminalNode LISTDECL() { return GetToken(GrammarParser.LISTDECL, 0); }
		public Parameter_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter_decl; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterParameter_decl(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitParameter_decl(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameter_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Parameter_declContext parameter_decl() {
		Parameter_declContext _localctx = new Parameter_declContext(Context, State);
		EnterRule(_localctx, 12, RULE_parameter_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 144;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INTDECL) | (1L << FLOATDECL) | (1L << BOOLDECL))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 146;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LISTDECL) {
				{
				State = 145; Match(LISTDECL);
				}
			}

			State = 148; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_stmtContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GrammarParser.IDENTIFIER, 0); }
		public Parameter_declContext[] parameter_decl() {
			return GetRuleContexts<Parameter_declContext>();
		}
		public Parameter_declContext parameter_decl(int i) {
			return GetRuleContext<Parameter_declContext>(i);
		}
		public Return_stmtContext return_stmt() {
			return GetRuleContext<Return_stmtContext>(0);
		}
		public ITerminalNode INTDECL() { return GetToken(GrammarParser.INTDECL, 0); }
		public ITerminalNode FLOATDECL() { return GetToken(GrammarParser.FLOATDECL, 0); }
		public ITerminalNode BOOLDECL() { return GetToken(GrammarParser.BOOLDECL, 0); }
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public ITerminalNode VOID() { return GetToken(GrammarParser.VOID, 0); }
		public Func_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterFunc_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitFunc_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_stmtContext func_stmt() {
		Func_stmtContext _localctx = new Func_stmtContext(Context, State);
		EnterRule(_localctx, 14, RULE_func_stmt);
		int _la;
		try {
			State = 187;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTDECL:
			case FLOATDECL:
			case BOOLDECL:
				EnterOuterAlt(_localctx, 1);
				{
				State = 150;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INTDECL) | (1L << FLOATDECL) | (1L << BOOLDECL))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 151; Match(IDENTIFIER);
				State = 152; Match(T__7);
				State = 153; parameter_decl();
				State = 158;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__6) {
					{
					{
					State = 154; Match(T__6);
					State = 155; parameter_decl();
					}
					}
					State = 160;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 161; Match(T__8);
				State = 162; Match(T__1);
				State = 164;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
				case 1:
					{
					State = 163; stmts();
					}
					break;
				}
				State = 166; return_stmt();
				State = 167; Match(T__2);
				}
				break;
			case VOID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 169; Match(VOID);
				State = 170; Match(IDENTIFIER);
				State = 171; Match(T__7);
				State = 172; parameter_decl();
				State = 177;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__6) {
					{
					{
					State = 173; Match(T__6);
					State = 174; parameter_decl();
					}
					}
					State = 179;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 180; Match(T__8);
				State = 181; Match(T__1);
				State = 183;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
				case 1:
					{
					State = 182; stmts();
					}
					break;
				}
				State = 185; Match(T__2);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_exprContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GrammarParser.IDENTIFIER, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public Logic_exprContext[] logic_expr() {
			return GetRuleContexts<Logic_exprContext>();
		}
		public Logic_exprContext logic_expr(int i) {
			return GetRuleContext<Logic_exprContext>(i);
		}
		public Func_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterFunc_expr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitFunc_expr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_exprContext func_expr() {
		Func_exprContext _localctx = new Func_exprContext(Context, State);
		EnterRule(_localctx, 16, RULE_func_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 189; Match(IDENTIFIER);
			State = 190; Match(T__7);
			State = 205;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__7) | (1L << BOOL) | (1L << IDENTIFIER) | (1L << INT) | (1L << FLOAT))) != 0)) {
				{
				State = 193;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,26,Context) ) {
				case 1:
					{
					State = 191; expr();
					}
					break;
				case 2:
					{
					State = 192; logic_expr();
					}
					break;
				}
				State = 202;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__6) {
					{
					{
					State = 195; Match(T__6);
					State = 198;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
					case 1:
						{
						State = 196; expr();
						}
						break;
					case 2:
						{
						State = 197; logic_expr();
						}
						break;
					}
					}
					}
					State = 204;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 207; Match(T__8);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Iter_stmtContext : ParserRuleContext {
		public ITerminalNode WHILE() { return GetToken(GrammarParser.WHILE, 0); }
		public Logic_exprContext logic_expr() {
			return GetRuleContext<Logic_exprContext>(0);
		}
		public StmtsContext stmts() {
			return GetRuleContext<StmtsContext>(0);
		}
		public ITerminalNode FOR() { return GetToken(GrammarParser.FOR, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(GrammarParser.IDENTIFIER, 0); }
		public ITerminalNode[] INT() { return GetTokens(GrammarParser.INT); }
		public ITerminalNode INT(int i) {
			return GetToken(GrammarParser.INT, i);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public Iter_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iter_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterIter_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitIter_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIter_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Iter_stmtContext iter_stmt() {
		Iter_stmtContext _localctx = new Iter_stmtContext(Context, State);
		EnterRule(_localctx, 18, RULE_iter_stmt);
		try {
			State = 234;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case WHILE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 209; Match(WHILE);
				State = 210; logic_expr();
				State = 211; Match(T__1);
				State = 213;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,30,Context) ) {
				case 1:
					{
					State = 212; stmts();
					}
					break;
				}
				State = 215; Match(T__2);
				}
				break;
			case FOR:
				EnterOuterAlt(_localctx, 2);
				{
				State = 217; Match(FOR);
				State = 218; Match(IDENTIFIER);
				State = 219; Match(T__3);
				State = 222;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
				case 1:
					{
					State = 220; Match(INT);
					}
					break;
				case 2:
					{
					State = 221; expr();
					}
					break;
				}
				State = 224; Match(T__9);
				State = 227;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,32,Context) ) {
				case 1:
					{
					State = 225; Match(INT);
					}
					break;
				case 2:
					{
					State = 226; expr();
					}
					break;
				}
				State = 229; Match(T__1);
				State = 231;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,33,Context) ) {
				case 1:
					{
					State = 230; stmts();
					}
					break;
				}
				State = 233; Match(T__2);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintContext : ParserRuleContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Logic_exprContext logic_expr() {
			return GetRuleContext<Logic_exprContext>(0);
		}
		public PrintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_print; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterPrint(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitPrint(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintContext print() {
		PrintContext _localctx = new PrintContext(Context, State);
		EnterRule(_localctx, 20, RULE_print);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 236; Match(T__10);
			State = 239;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,35,Context) ) {
			case 1:
				{
				State = 237; expr();
				}
				break;
			case 2:
				{
				State = 238; logic_expr();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Var_exprContext var_expr() {
			return GetRuleContext<Var_exprContext>(0);
		}
		public Num_exprContext num_expr() {
			return GetRuleContext<Num_exprContext>(0);
		}
		public Func_exprContext func_expr() {
			return GetRuleContext<Func_exprContext>(0);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		ExprContext _localctx = new ExprContext(Context, State);
		EnterRule(_localctx, 22, RULE_expr);
		int _la;
		try {
			State = 249;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,37,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 241; Match(T__7);
				State = 243;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__7) | (1L << IDENTIFIER) | (1L << INT) | (1L << FLOAT))) != 0)) {
					{
					State = 242; expr();
					}
				}

				State = 245; Match(T__8);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 246; var_expr();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 247; num_expr(0);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 248; func_expr();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_exprContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(GrammarParser.IDENTIFIER, 0); }
		public Num_exprContext num_expr() {
			return GetRuleContext<Num_exprContext>(0);
		}
		public Var_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterVar_expr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitVar_expr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_exprContext var_expr() {
		Var_exprContext _localctx = new Var_exprContext(Context, State);
		EnterRule(_localctx, 24, RULE_var_expr);
		try {
			State = 257;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,38,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 251; Match(IDENTIFIER);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 252; Match(IDENTIFIER);
				State = 253; Match(T__4);
				State = 254; num_expr(0);
				State = 255; Match(T__5);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Num_exprContext : ParserRuleContext {
		public IToken op;
		public Var_exprContext var_expr() {
			return GetRuleContext<Var_exprContext>(0);
		}
		public ITerminalNode INT() { return GetToken(GrammarParser.INT, 0); }
		public ITerminalNode FLOAT() { return GetToken(GrammarParser.FLOAT, 0); }
		public Num_exprContext[] num_expr() {
			return GetRuleContexts<Num_exprContext>();
		}
		public Num_exprContext num_expr(int i) {
			return GetRuleContext<Num_exprContext>(i);
		}
		public ITerminalNode MUL() { return GetToken(GrammarParser.MUL, 0); }
		public ITerminalNode DIV() { return GetToken(GrammarParser.DIV, 0); }
		public ITerminalNode ADD() { return GetToken(GrammarParser.ADD, 0); }
		public ITerminalNode SUB() { return GetToken(GrammarParser.SUB, 0); }
		public Num_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_num_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterNum_expr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitNum_expr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNum_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Num_exprContext num_expr() {
		return num_expr(0);
	}

	private Num_exprContext num_expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		Num_exprContext _localctx = new Num_exprContext(Context, _parentState);
		Num_exprContext _prevctx = _localctx;
		int _startState = 26;
		EnterRecursionRule(_localctx, 26, RULE_num_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 263;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
				{
				State = 260; var_expr();
				}
				break;
			case INT:
				{
				State = 261; Match(INT);
				}
				break;
			case FLOAT:
				{
				State = 262; Match(FLOAT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 273;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,41,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 271;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,40,Context) ) {
					case 1:
						{
						_localctx = new Num_exprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_num_expr);
						State = 265;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 266;
						_localctx.op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==MUL || _la==DIV) ) {
							_localctx.op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 267; num_expr(6);
						}
						break;
					case 2:
						{
						_localctx = new Num_exprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_num_expr);
						State = 268;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 269;
						_localctx.op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==ADD || _la==SUB) ) {
							_localctx.op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 270; num_expr(5);
						}
						break;
					}
					} 
				}
				State = 275;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,41,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Logic_exprContext : ParserRuleContext {
		public IToken op;
		public Logic_exprContext[] logic_expr() {
			return GetRuleContexts<Logic_exprContext>();
		}
		public Logic_exprContext logic_expr(int i) {
			return GetRuleContext<Logic_exprContext>(i);
		}
		public ITerminalNode BOOL() { return GetToken(GrammarParser.BOOL, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode LT() { return GetToken(GrammarParser.LT, 0); }
		public ITerminalNode LTEQ() { return GetToken(GrammarParser.LTEQ, 0); }
		public ITerminalNode GT() { return GetToken(GrammarParser.GT, 0); }
		public ITerminalNode GTEQ() { return GetToken(GrammarParser.GTEQ, 0); }
		public ITerminalNode[] AND() { return GetTokens(GrammarParser.AND); }
		public ITerminalNode AND(int i) {
			return GetToken(GrammarParser.AND, i);
		}
		public ITerminalNode[] OR() { return GetTokens(GrammarParser.OR); }
		public ITerminalNode OR(int i) {
			return GetToken(GrammarParser.OR, i);
		}
		public ITerminalNode EQ() { return GetToken(GrammarParser.EQ, 0); }
		public ITerminalNode NEQ() { return GetToken(GrammarParser.NEQ, 0); }
		public Logic_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logic_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterLogic_expr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitLogic_expr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogic_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Logic_exprContext logic_expr() {
		Logic_exprContext _localctx = new Logic_exprContext(Context, State);
		EnterRule(_localctx, 28, RULE_logic_expr);
		int _la;
		try {
			int _alt;
			State = 301;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,44,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 276; Match(T__7);
				State = 277; logic_expr();
				State = 278; Match(T__8);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 280; Match(BOOL);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 281; expr();
				State = 282;
				_localctx.op = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LT) | (1L << GT) | (1L << GTEQ) | (1L << LTEQ))) != 0)) ) {
					_localctx.op = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 283; expr();
				State = 288;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,42,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 284;
						_localctx.op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==AND || _la==OR) ) {
							_localctx.op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 285; logic_expr();
						}
						} 
					}
					State = 290;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,42,Context);
				}
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 291; expr();
				State = 292;
				_localctx.op = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==NEQ || _la==EQ) ) {
					_localctx.op = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 293; expr();
				State = 298;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,43,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 294;
						_localctx.op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==AND || _la==OR) ) {
							_localctx.op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 295; logic_expr();
						}
						} 
					}
					State = 300;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,43,Context);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Return_stmtContext : ParserRuleContext {
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Logic_exprContext logic_expr() {
			return GetRuleContext<Logic_exprContext>(0);
		}
		public Return_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_return_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterReturn_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitReturn_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturn_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Return_stmtContext return_stmt() {
		Return_stmtContext _localctx = new Return_stmtContext(Context, State);
		EnterRule(_localctx, 30, RULE_return_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 303; Match(T__11);
			State = 306;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,45,Context) ) {
			case 1:
				{
				State = 304; expr();
				}
				break;
			case 2:
				{
				State = 305; logic_expr();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CompileUnitContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(GrammarParser.Eof, 0); }
		public CompileUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compileUnit; } }
		public override void EnterRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.EnterCompileUnit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IGrammarListener typedListener = listener as IGrammarListener;
			if (typedListener != null) typedListener.ExitCompileUnit(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IGrammarVisitor<TResult> typedVisitor = visitor as IGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompileUnit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompileUnitContext compileUnit() {
		CompileUnitContext _localctx = new CompileUnitContext(Context, State);
		EnterRule(_localctx, 32, RULE_compileUnit);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 308; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 13: return num_expr_sempred((Num_exprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool num_expr_sempred(Num_exprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 5);
		case 1: return Precpred(Context, 4);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '+', '\x139', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x3', '\x2', '\x3', 
		'\x2', '\a', '\x2', '\'', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '*', 
		'\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', '\x2', '/', 
		'\n', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\a', '\x3', '\x34', 
		'\n', '\x3', '\f', '\x3', '\xE', '\x3', '\x37', '\v', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x5', '\x4', '?', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x5', '\x5', '\x45', '\n', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x5', '\x5', 'N', '\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x5', '\x5', 'T', '\n', '\x5', '\x5', '\x5', 'V', 
		'\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x5', '\x6', ']', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x5', 
		'\x6', '\x66', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x5', '\x6', 'k', '\n', '\x6', '\a', '\x6', 'm', '\n', '\x6', '\f', '\x6', 
		'\xE', '\x6', 'p', '\v', '\x6', '\x5', '\x6', 'r', '\n', '\x6', '\x3', 
		'\x6', '\x5', '\x6', 'u', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x5', '\a', '{', '\n', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', '\x82', '\n', '\a', 
		'\x3', '\a', '\x3', '\a', '\a', '\a', '\x86', '\n', '\a', '\f', '\a', 
		'\xE', '\a', '\x89', '\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x5', '\a', '\x8E', '\n', '\a', '\x3', '\a', '\x5', '\a', '\x91', '\n', 
		'\a', '\x3', '\b', '\x3', '\b', '\x5', '\b', '\x95', '\n', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\a', '\t', '\x9F', '\n', '\t', '\f', '\t', 
		'\xE', '\t', '\xA2', '\v', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x5', '\t', '\xA7', '\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\a', '\t', '\xB2', '\n', '\t', '\f', '\t', '\xE', '\t', '\xB5', 
		'\v', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\xBA', 
		'\n', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\xBE', '\n', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', '\xC4', 
		'\n', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', '\xC9', 
		'\n', '\n', '\a', '\n', '\xCB', '\n', '\n', '\f', '\n', '\xE', '\n', '\xCE', 
		'\v', '\n', '\x5', '\n', '\xD0', '\n', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', '\xD8', 
		'\n', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', '\xE1', '\n', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', '\xE6', '\n', '\v', '\x3', 
		'\v', '\x3', '\v', '\x5', '\v', '\xEA', '\n', '\v', '\x3', '\v', '\x5', 
		'\v', '\xED', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x5', 
		'\f', '\xF2', '\n', '\f', '\x3', '\r', '\x3', '\r', '\x5', '\r', '\xF6', 
		'\n', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', 
		'\r', '\xFC', '\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', '\x104', '\n', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', 
		'\x10A', '\n', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\a', '\xF', '\x112', '\n', '\xF', 
		'\f', '\xF', '\xE', '\xF', '\x115', '\v', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\a', '\x10', '\x121', 
		'\n', '\x10', '\f', '\x10', '\xE', '\x10', '\x124', '\v', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\a', 
		'\x10', '\x12B', '\n', '\x10', '\f', '\x10', '\xE', '\x10', '\x12E', '\v', 
		'\x10', '\x5', '\x10', '\x130', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x5', '\x11', '\x135', '\n', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x2', '\x3', '\x1C', '\x13', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', 
		'\x1C', '\x1E', ' ', '\"', '\x2', '\b', '\x3', '\x2', '\x18', '\x1A', 
		'\x3', '\x2', '\"', '#', '\x3', '\x2', '$', '%', '\x3', '\x2', '\x12', 
		'\x15', '\x3', '\x2', '\x10', '\x11', '\x3', '\x2', '\x16', '\x17', '\x2', 
		'\x15F', '\x2', '(', '\x3', '\x2', '\x2', '\x2', '\x4', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x6', '>', '\x3', '\x2', '\x2', '\x2', '\b', 'U', 
		'\x3', '\x2', '\x2', '\x2', '\n', 't', '\x3', '\x2', '\x2', '\x2', '\f', 
		'v', '\x3', '\x2', '\x2', '\x2', '\xE', '\x92', '\x3', '\x2', '\x2', '\x2', 
		'\x10', '\xBD', '\x3', '\x2', '\x2', '\x2', '\x12', '\xBF', '\x3', '\x2', 
		'\x2', '\x2', '\x14', '\xEC', '\x3', '\x2', '\x2', '\x2', '\x16', '\xEE', 
		'\x3', '\x2', '\x2', '\x2', '\x18', '\xFB', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', '\x103', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x109', '\x3', '\x2', 
		'\x2', '\x2', '\x1E', '\x12F', '\x3', '\x2', '\x2', '\x2', ' ', '\x131', 
		'\x3', '\x2', '\x2', '\x2', '\"', '\x136', '\x3', '\x2', '\x2', '\x2', 
		'$', '\'', '\x5', '\b', '\x5', '\x2', '%', '\'', '\x5', '\x10', '\t', 
		'\x2', '&', '$', '\x3', '\x2', '\x2', '\x2', '&', '%', '\x3', '\x2', '\x2', 
		'\x2', '\'', '*', '\x3', '\x2', '\x2', '\x2', '(', '&', '\x3', '\x2', 
		'\x2', '\x2', '(', ')', '\x3', '\x2', '\x2', '\x2', ')', '+', '\x3', '\x2', 
		'\x2', '\x2', '*', '(', '\x3', '\x2', '\x2', '\x2', '+', ',', '\a', '\x3', 
		'\x2', '\x2', ',', '.', '\a', '\x4', '\x2', '\x2', '-', '/', '\x5', '\x4', 
		'\x3', '\x2', '.', '-', '\x3', '\x2', '\x2', '\x2', '.', '/', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x30', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', 
		'\a', '\x5', '\x2', '\x2', '\x31', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x32', '\x34', '\x5', '\x6', '\x4', '\x2', '\x33', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\x34', '\x37', '\x3', '\x2', '\x2', '\x2', '\x35', '\x33', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\x3', '\x2', '\x2', '\x2', 
		'\x36', '\x5', '\x3', '\x2', '\x2', '\x2', '\x37', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x38', '?', '\x5', '\b', '\x5', '\x2', '\x39', '?', '\x5', 
		'\n', '\x6', '\x2', ':', '?', '\x5', '\x14', '\v', '\x2', ';', '?', '\x5', 
		'\f', '\a', '\x2', '<', '?', '\x5', '\x12', '\n', '\x2', '=', '?', '\x5', 
		'\x16', '\f', '\x2', '>', '\x38', '\x3', '\x2', '\x2', '\x2', '>', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '>', ':', '\x3', '\x2', '\x2', '\x2', '>', 
		';', '\x3', '\x2', '\x2', '\x2', '>', '<', '\x3', '\x2', '\x2', '\x2', 
		'>', '=', '\x3', '\x2', '\x2', '\x2', '?', '\a', '\x3', '\x2', '\x2', 
		'\x2', '@', '\x41', '\a', '\'', '\x2', '\x2', '\x41', '\x44', '\a', '\x6', 
		'\x2', '\x2', '\x42', '\x45', '\x5', '\x18', '\r', '\x2', '\x43', '\x45', 
		'\x5', '\x1E', '\x10', '\x2', '\x44', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\x44', '\x43', '\x3', '\x2', '\x2', '\x2', '\x45', 'V', '\x3', '\x2', 
		'\x2', '\x2', '\x46', 'G', '\a', '\'', '\x2', '\x2', 'G', 'H', '\a', '\a', 
		'\x2', '\x2', 'H', 'I', '\x5', '\x1C', '\xF', '\x2', 'I', 'J', '\a', '\b', 
		'\x2', '\x2', 'J', 'M', '\a', '\x6', '\x2', '\x2', 'K', 'N', '\x5', '\x18', 
		'\r', '\x2', 'L', 'N', '\x5', '\x1E', '\x10', '\x2', 'M', 'K', '\x3', 
		'\x2', '\x2', '\x2', 'M', 'L', '\x3', '\x2', '\x2', '\x2', 'N', 'V', '\x3', 
		'\x2', '\x2', '\x2', 'O', 'P', '\a', '\'', '\x2', '\x2', 'P', 'S', '\a', 
		'\xF', '\x2', '\x2', 'Q', 'T', '\x5', '\x18', '\r', '\x2', 'R', 'T', '\x5', 
		'\x1E', '\x10', '\x2', 'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'R', 
		'\x3', '\x2', '\x2', '\x2', 'T', 'V', '\x3', '\x2', '\x2', '\x2', 'U', 
		'@', '\x3', '\x2', '\x2', '\x2', 'U', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'U', 'O', '\x3', '\x2', '\x2', '\x2', 'V', '\t', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\t', '\x2', '\x2', '\x2', 'X', 'Y', '\a', '\'', '\x2', 
		'\x2', 'Y', '\\', '\a', '\x6', '\x2', '\x2', 'Z', ']', '\x5', '\x18', 
		'\r', '\x2', '[', ']', '\x5', '\x1E', '\x10', '\x2', '\\', 'Z', '\x3', 
		'\x2', '\x2', '\x2', '\\', '[', '\x3', '\x2', '\x2', '\x2', ']', 'u', 
		'\x3', '\x2', '\x2', '\x2', '^', '_', '\t', '\x2', '\x2', '\x2', '_', 
		'`', '\a', '\x1B', '\x2', '\x2', '`', '\x61', '\a', '\'', '\x2', '\x2', 
		'\x61', '\x62', '\a', '\x6', '\x2', '\x2', '\x62', 'q', '\a', '\a', '\x2', 
		'\x2', '\x63', '\x66', '\x5', '\x18', '\r', '\x2', '\x64', '\x66', '\x5', 
		'\x1E', '\x10', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x66', 'n', '\x3', '\x2', '\x2', 
		'\x2', 'g', 'j', '\a', '\t', '\x2', '\x2', 'h', 'k', '\x5', '\x18', '\r', 
		'\x2', 'i', 'k', '\x5', '\x1E', '\x10', '\x2', 'j', 'h', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'i', '\x3', '\x2', '\x2', '\x2', 'k', 'm', '\x3', '\x2', 
		'\x2', '\x2', 'l', 'g', '\x3', '\x2', '\x2', '\x2', 'm', 'p', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', 
		'\x2', '\x2', 'o', 'r', '\x3', '\x2', '\x2', '\x2', 'p', 'n', '\x3', '\x2', 
		'\x2', '\x2', 'q', '\x65', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\x3', 
		'\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 's', 'u', '\a', 
		'\b', '\x2', '\x2', 't', 'W', '\x3', '\x2', '\x2', '\x2', 't', '^', '\x3', 
		'\x2', '\x2', '\x2', 'u', '\v', '\x3', '\x2', '\x2', '\x2', 'v', 'w', 
		'\a', '\x1D', '\x2', '\x2', 'w', 'x', '\x5', '\x1E', '\x10', '\x2', 'x', 
		'z', '\a', '\x4', '\x2', '\x2', 'y', '{', '\x5', '\x4', '\x3', '\x2', 
		'z', 'y', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\x3', '\x2', '\x2', '\x2', 
		'{', '|', '\x3', '\x2', '\x2', '\x2', '|', '\x87', '\a', '\x5', '\x2', 
		'\x2', '}', '~', '\a', '\x1E', '\x2', '\x2', '~', '\x7F', '\x5', '\x1E', 
		'\x10', '\x2', '\x7F', '\x81', '\a', '\x4', '\x2', '\x2', '\x80', '\x82', 
		'\x5', '\x4', '\x3', '\x2', '\x81', '\x80', '\x3', '\x2', '\x2', '\x2', 
		'\x81', '\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\x3', '\x2', 
		'\x2', '\x2', '\x83', '\x84', '\a', '\x5', '\x2', '\x2', '\x84', '\x86', 
		'\x3', '\x2', '\x2', '\x2', '\x85', '}', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'\x89', '\x3', '\x2', '\x2', '\x2', '\x87', '\x85', '\x3', '\x2', '\x2', 
		'\x2', '\x87', '\x88', '\x3', '\x2', '\x2', '\x2', '\x88', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x87', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8B', '\a', '\x1F', '\x2', '\x2', '\x8B', '\x8D', '\a', '\x4', '\x2', 
		'\x2', '\x8C', '\x8E', '\x5', '\x4', '\x3', '\x2', '\x8D', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x91', '\a', '\x5', '\x2', 
		'\x2', '\x90', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\r', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x94', '\t', '\x2', '\x2', '\x2', '\x93', '\x95', '\a', '\x1B', '\x2', 
		'\x2', '\x94', '\x93', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\x95', '\x96', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x97', '\a', '\'', '\x2', '\x2', '\x97', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x99', '\t', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', 
		'\'', '\x2', '\x2', '\x9A', '\x9B', '\a', '\n', '\x2', '\x2', '\x9B', 
		'\xA0', '\x5', '\xE', '\b', '\x2', '\x9C', '\x9D', '\a', '\t', '\x2', 
		'\x2', '\x9D', '\x9F', '\x5', '\xE', '\b', '\x2', '\x9E', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '\x9F', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\x9E', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\xA3', '\xA4', '\a', '\v', '\x2', '\x2', '\xA4', 
		'\xA6', '\a', '\x4', '\x2', '\x2', '\xA5', '\xA7', '\x5', '\x4', '\x3', 
		'\x2', '\xA6', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\x3', 
		'\x2', '\x2', '\x2', '\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xA9', '\x5', ' ', '\x11', '\x2', '\xA9', '\xAA', '\a', '\x5', '\x2', 
		'\x2', '\xAA', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\a', 
		'\x1C', '\x2', '\x2', '\xAC', '\xAD', '\a', '\'', '\x2', '\x2', '\xAD', 
		'\xAE', '\a', '\n', '\x2', '\x2', '\xAE', '\xB3', '\x5', '\xE', '\b', 
		'\x2', '\xAF', '\xB0', '\a', '\t', '\x2', '\x2', '\xB0', '\xB2', '\x5', 
		'\xE', '\b', '\x2', '\xB1', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB2', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB6', '\x3', 
		'\x2', '\x2', '\x2', '\xB5', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB6', 
		'\xB7', '\a', '\v', '\x2', '\x2', '\xB7', '\xB9', '\a', '\x4', '\x2', 
		'\x2', '\xB8', '\xBA', '\x5', '\x4', '\x3', '\x2', '\xB9', '\xB8', '\x3', 
		'\x2', '\x2', '\x2', '\xB9', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBA', 
		'\xBB', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBC', '\a', '\x5', '\x2', 
		'\x2', '\xBC', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xBD', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '\xBD', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\a', '\'', '\x2', 
		'\x2', '\xC0', '\xCF', '\a', '\n', '\x2', '\x2', '\xC1', '\xC4', '\x5', 
		'\x18', '\r', '\x2', '\xC2', '\xC4', '\x5', '\x1E', '\x10', '\x2', '\xC3', 
		'\xC1', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC2', '\x3', '\x2', '\x2', 
		'\x2', '\xC4', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC8', '\a', 
		'\t', '\x2', '\x2', '\xC6', '\xC9', '\x5', '\x18', '\r', '\x2', '\xC7', 
		'\xC9', '\x5', '\x1E', '\x10', '\x2', '\xC8', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\xC8', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\xCA', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xCB', 
		'\xCE', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\xCC', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xD0', '\x3', 
		'\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCF', 
		'\xC3', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '\xD0', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD2', '\a', 
		'\v', '\x2', '\x2', '\xD2', '\x13', '\x3', '\x2', '\x2', '\x2', '\xD3', 
		'\xD4', '\a', ' ', '\x2', '\x2', '\xD4', '\xD5', '\x5', '\x1E', '\x10', 
		'\x2', '\xD5', '\xD7', '\a', '\x4', '\x2', '\x2', '\xD6', '\xD8', '\x5', 
		'\x4', '\x3', '\x2', '\xD7', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD7', 
		'\xD8', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xD9', '\x3', '\x2', '\x2', 
		'\x2', '\xD9', '\xDA', '\a', '\x5', '\x2', '\x2', '\xDA', '\xED', '\x3', 
		'\x2', '\x2', '\x2', '\xDB', '\xDC', '\a', '!', '\x2', '\x2', '\xDC', 
		'\xDD', '\a', '\'', '\x2', '\x2', '\xDD', '\xE0', '\a', '\x6', '\x2', 
		'\x2', '\xDE', '\xE1', '\a', '(', '\x2', '\x2', '\xDF', '\xE1', '\x5', 
		'\x18', '\r', '\x2', '\xE0', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xE0', 
		'\xDF', '\x3', '\x2', '\x2', '\x2', '\xE1', '\xE2', '\x3', '\x2', '\x2', 
		'\x2', '\xE2', '\xE5', '\a', '\f', '\x2', '\x2', '\xE3', '\xE6', '\a', 
		'(', '\x2', '\x2', '\xE4', '\xE6', '\x5', '\x18', '\r', '\x2', '\xE5', 
		'\xE3', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE4', '\x3', '\x2', '\x2', 
		'\x2', '\xE6', '\xE7', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE9', '\a', 
		'\x4', '\x2', '\x2', '\xE8', '\xEA', '\x5', '\x4', '\x3', '\x2', '\xE9', 
		'\xE8', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xEA', '\x3', '\x2', '\x2', 
		'\x2', '\xEA', '\xEB', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xED', '\a', 
		'\x5', '\x2', '\x2', '\xEC', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xEC', 
		'\xDB', '\x3', '\x2', '\x2', '\x2', '\xED', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\xEE', '\xF1', '\a', '\r', '\x2', '\x2', '\xEF', '\xF2', '\x5', 
		'\x18', '\r', '\x2', '\xF0', '\xF2', '\x5', '\x1E', '\x10', '\x2', '\xF1', 
		'\xEF', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xF0', '\x3', '\x2', '\x2', 
		'\x2', '\xF2', '\x17', '\x3', '\x2', '\x2', '\x2', '\xF3', '\xF5', '\a', 
		'\n', '\x2', '\x2', '\xF4', '\xF6', '\x5', '\x18', '\r', '\x2', '\xF5', 
		'\xF4', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xF6', '\x3', '\x2', '\x2', 
		'\x2', '\xF6', '\xF7', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xFC', '\a', 
		'\v', '\x2', '\x2', '\xF8', '\xFC', '\x5', '\x1A', '\xE', '\x2', '\xF9', 
		'\xFC', '\x5', '\x1C', '\xF', '\x2', '\xFA', '\xFC', '\x5', '\x12', '\n', 
		'\x2', '\xFB', '\xF3', '\x3', '\x2', '\x2', '\x2', '\xFB', '\xF8', '\x3', 
		'\x2', '\x2', '\x2', '\xFB', '\xF9', '\x3', '\x2', '\x2', '\x2', '\xFB', 
		'\xFA', '\x3', '\x2', '\x2', '\x2', '\xFC', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\xFD', '\x104', '\a', '\'', '\x2', '\x2', '\xFE', '\xFF', '\a', 
		'\'', '\x2', '\x2', '\xFF', '\x100', '\a', '\a', '\x2', '\x2', '\x100', 
		'\x101', '\x5', '\x1C', '\xF', '\x2', '\x101', '\x102', '\a', '\b', '\x2', 
		'\x2', '\x102', '\x104', '\x3', '\x2', '\x2', '\x2', '\x103', '\xFD', 
		'\x3', '\x2', '\x2', '\x2', '\x103', '\xFE', '\x3', '\x2', '\x2', '\x2', 
		'\x104', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x105', '\x106', '\b', '\xF', 
		'\x1', '\x2', '\x106', '\x10A', '\x5', '\x1A', '\xE', '\x2', '\x107', 
		'\x10A', '\a', '(', '\x2', '\x2', '\x108', '\x10A', '\a', ')', '\x2', 
		'\x2', '\x109', '\x105', '\x3', '\x2', '\x2', '\x2', '\x109', '\x107', 
		'\x3', '\x2', '\x2', '\x2', '\x109', '\x108', '\x3', '\x2', '\x2', '\x2', 
		'\x10A', '\x113', '\x3', '\x2', '\x2', '\x2', '\x10B', '\x10C', '\f', 
		'\a', '\x2', '\x2', '\x10C', '\x10D', '\t', '\x3', '\x2', '\x2', '\x10D', 
		'\x112', '\x5', '\x1C', '\xF', '\b', '\x10E', '\x10F', '\f', '\x6', '\x2', 
		'\x2', '\x10F', '\x110', '\t', '\x4', '\x2', '\x2', '\x110', '\x112', 
		'\x5', '\x1C', '\xF', '\a', '\x111', '\x10B', '\x3', '\x2', '\x2', '\x2', 
		'\x111', '\x10E', '\x3', '\x2', '\x2', '\x2', '\x112', '\x115', '\x3', 
		'\x2', '\x2', '\x2', '\x113', '\x111', '\x3', '\x2', '\x2', '\x2', '\x113', 
		'\x114', '\x3', '\x2', '\x2', '\x2', '\x114', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x115', '\x113', '\x3', '\x2', '\x2', '\x2', '\x116', '\x117', 
		'\a', '\n', '\x2', '\x2', '\x117', '\x118', '\x5', '\x1E', '\x10', '\x2', 
		'\x118', '\x119', '\a', '\v', '\x2', '\x2', '\x119', '\x130', '\x3', '\x2', 
		'\x2', '\x2', '\x11A', '\x130', '\a', '&', '\x2', '\x2', '\x11B', '\x11C', 
		'\x5', '\x18', '\r', '\x2', '\x11C', '\x11D', '\t', '\x5', '\x2', '\x2', 
		'\x11D', '\x122', '\x5', '\x18', '\r', '\x2', '\x11E', '\x11F', '\t', 
		'\x6', '\x2', '\x2', '\x11F', '\x121', '\x5', '\x1E', '\x10', '\x2', '\x120', 
		'\x11E', '\x3', '\x2', '\x2', '\x2', '\x121', '\x124', '\x3', '\x2', '\x2', 
		'\x2', '\x122', '\x120', '\x3', '\x2', '\x2', '\x2', '\x122', '\x123', 
		'\x3', '\x2', '\x2', '\x2', '\x123', '\x130', '\x3', '\x2', '\x2', '\x2', 
		'\x124', '\x122', '\x3', '\x2', '\x2', '\x2', '\x125', '\x126', '\x5', 
		'\x18', '\r', '\x2', '\x126', '\x127', '\t', '\a', '\x2', '\x2', '\x127', 
		'\x12C', '\x5', '\x18', '\r', '\x2', '\x128', '\x129', '\t', '\x6', '\x2', 
		'\x2', '\x129', '\x12B', '\x5', '\x1E', '\x10', '\x2', '\x12A', '\x128', 
		'\x3', '\x2', '\x2', '\x2', '\x12B', '\x12E', '\x3', '\x2', '\x2', '\x2', 
		'\x12C', '\x12A', '\x3', '\x2', '\x2', '\x2', '\x12C', '\x12D', '\x3', 
		'\x2', '\x2', '\x2', '\x12D', '\x130', '\x3', '\x2', '\x2', '\x2', '\x12E', 
		'\x12C', '\x3', '\x2', '\x2', '\x2', '\x12F', '\x116', '\x3', '\x2', '\x2', 
		'\x2', '\x12F', '\x11A', '\x3', '\x2', '\x2', '\x2', '\x12F', '\x11B', 
		'\x3', '\x2', '\x2', '\x2', '\x12F', '\x125', '\x3', '\x2', '\x2', '\x2', 
		'\x130', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x131', '\x134', '\a', '\xE', 
		'\x2', '\x2', '\x132', '\x135', '\x5', '\x18', '\r', '\x2', '\x133', '\x135', 
		'\x5', '\x1E', '\x10', '\x2', '\x134', '\x132', '\x3', '\x2', '\x2', '\x2', 
		'\x134', '\x133', '\x3', '\x2', '\x2', '\x2', '\x135', '!', '\x3', '\x2', 
		'\x2', '\x2', '\x136', '\x137', '\a', '\x2', '\x2', '\x3', '\x137', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x30', '&', '(', '.', '\x35', '>', '\x44', 
		'M', 'S', 'U', '\\', '\x65', 'j', 'n', 'q', 't', 'z', '\x81', '\x87', 
		'\x8D', '\x90', '\x94', '\xA0', '\xA6', '\xB3', '\xB9', '\xBD', '\xC3', 
		'\xC8', '\xCC', '\xCF', '\xD7', '\xE0', '\xE5', '\xE9', '\xEC', '\xF1', 
		'\xF5', '\xFB', '\x103', '\x109', '\x111', '\x113', '\x122', '\x12C', 
		'\x12F', '\x134',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
